""" Constants to be used for utilities """
VERBOSE_FALSE = 0
VERBOSE_VERY_LOW = 0.5
VERBOSE_BASIC = 1
VERBOSE_TRUE = 2
VERBOSE_VERY_HIGH = 3

MQTT_BROKER_ADDRESS = "localhost"
MQTT_CLIENT_TYPE_LISTENER = "MQTT_CLIENT_TYPE_LISTENER"
MQTT_CLIENT_TYPE_PUBLISHER = "MQTT_CLIENT_TYPE_PUBLISHER"

TOPIC_DISTANCE = "NAO_TOPIC_DISTANCE"
TOPIC_HUMAN_DETECTION = "NAO_TOPIC_HUMAN_DETECTED"
TOPIC_DIRECTIVE = "NAO_TOPIC_DIRECTIVE"
TOPIC_IMAGE = "NAO_TOPIC_IMAGE"
TOPIC_SPEECH = "NAO_TOPIC_SPEECH"
TOPIC_POSTURE = "NAO_TOPIC_POSTURE"
TOPIC_SOCIAL_INTERPR = "NAO_TOPIC_SOCIAL_INTERPR"


LV_DUTY = "DUTY"
LV_INTELLECT = "INTELLECT"
LV_ADVERSITY = "ADVERSITY"
LV_MATING = "MATING"
LV_POSITIVITY = "POSITIVITY"
LV_NEGATIVITY = "NEGATIVITY"
LV_DECEPTION = "DECEPTION"
LV_SOCIALITY = "SOCIALITY"

LV_DIST = "DIST"
LV_VOLUME = "VOLUME"
LV_MOVEMENTS = "MOVEMENTS"

SOCIAL_INTERPRETATIONS = [
    LV_DUTY,            # D
    LV_INTELLECT,       # I
    LV_ADVERSITY,       # A
    LV_MATING,          # M
    LV_POSITIVITY,      # O
    LV_NEGATIVITY,      # N
    LV_DECEPTION,       # D
    LV_SOCIALITY        # S
]

LV_FAMILY = "FAMILY"
LV_MATE = "MATE"
LV_FRIENDS = "FRIENDS"
LV_COHABITANTS = "COHABITANTS"
LV_COLLEAGUES = "COLLEAGUES"
LV_ALONE = "ALONE"
LV_SPORTS = "SPORTS"
LV_EXAM = "EXAM"
LV_FOOD = "FOOD"
LV_EATING = "EATING"
LV_DRINKING = "DRINKING"
LV_COMMUNICATING = "COMMUNICATING"
LV_TV = "TV"
LV_COMMUTING = "COMMUTING"
LV_COMPUTER = "COMPUTER"
LV_VIDEOGAMES = "VIDEOGAMES"
LV_READING = "READING"
LV_WORKING = "WORKING"
LV_SHOPPING = "SHOPPING"
LV_GROOMING = "GROOMING"
LV_WAITING = "WAITING"
LV_SLEEP = "SLEEP"
LV_MUSIC = "MUSIC"
LV_TELEPHONE = "TELEPHONE"
LV_HOME = "HOME"
LV_BATHROOM = "BATHROOM"
LV_KITCHEN = "KITCHEN"
LV_BED = "BED"
LV_UNIVERSITY = "UNIVERSITY"
LV_BAR = "BAR"

LV_SOCIAL_CUES = [LV_FAMILY,
LV_MATE,
LV_FRIENDS,
LV_COHABITANTS,
LV_COLLEAGUES,
LV_ALONE,
LV_SPORTS,
LV_EXAM,
LV_FOOD,
LV_EATING,
LV_DRINKING,
LV_COMMUNICATING,
LV_TV,
LV_COMMUTING,
LV_COMPUTER,
LV_VIDEOGAMES,
LV_READING,
LV_WORKING,
LV_SHOPPING,
LV_GROOMING,
LV_WAITING,
LV_SLEEP,
LV_MUSIC,
LV_TELEPHONE,
LV_HOME,
LV_BATHROOM,
LV_KITCHEN,
LV_BED,
LV_UNIVERSITY,
LV_BAR]

STATIC_LV = LV_SOCIAL_CUES
DYNAMIC_LV = [LV_DIST, LV_VOLUME, LV_MOVEMENTS]

ACTUATION_ASPECT_CHATTER = "chat_qualifier"
ACTUATION_ASPECT_SYSTEM = "system_qualifier"
ACTUATION_ASPECT_POSITION = "position_qualifier"
ACTUATION_ASPECT_POSTURE = "posture_qualifier"
ACTUATION_ASPECTS = [
    ACTUATION_ASPECT_CHATTER,
    ACTUATION_ASPECT_SYSTEM,
    ACTUATION_ASPECT_POSITION,
    ACTUATION_ASPECT_POSTURE
]

BDI_CORE_JID = "sarbdicoreagent@localhost"
BDI_CORE_PWD = "bdicore"
CHATTER_JID = "sarchatter@localhost"
CHATTER_PWD = "chatter"
DATACOLLECTOR_JID = "sardatacollector@localhost"
DATACOLLECTOR_PWD = "collector"
SYSTEM_HANDLER_JID = "sarsystemhandler@localhost"
SYSTEM_HANDLER_PWD = "handler"
POSITION_HANDLER_JID = "sarpositionhandler@localhost"
POSITION_HANDLER_PWD = "position"
VISION_HANDLER_JID = "sarvisionhandler@localhost"
VISION_HANDLER_PWD = "vision"
POSTURE_HANDLER_JID = "sarposturehandler@localhost"
POSTURE_HANDLER_PWD = "posture"
NORMADAPTER_JID = "sarnormadapter@localhost"
NORMADAPTER_PWD = "norm"

PERFORMATIVE_INFORM = "inform"
PERFORMATIVE_REQUEST = "request"
PERFORMATIVE_NEW_BELIEF = "newbel"

STRING_SEPARATOR = ";;"
BEL_STRING_SEPARATOR = "**"
ASL_STRING_SEPARATOR = "__"

DIRECTIVE_SHUT_DOWN = "shut_down"
DIRECTIVE_SAY = "say"
DIRECTIVE_REPLY_TO = "reply_to"
DIRECTIVE_GOTOPOSTURE = "go_to_posture"

POSTURE_SIT = "Sit"
POSTURE_CROUCH = "Crouch"
POSTURE_LAYINGBACK = "LayingBack"
POSTURE_LAYINGBELLY = "LayingBelly"
POSTURE_STAND = "Stand"

POSTURES = {"sit": POSTURE_SIT,
            "sit" + ASL_STRING_SEPARATOR + "down": POSTURE_SIT,
            "crouch": POSTURE_CROUCH,
            "lay" + ASL_STRING_SEPARATOR + "back": POSTURE_LAYINGBACK,
            "lay" + ASL_STRING_SEPARATOR + "belly": POSTURE_LAYINGBELLY,
            "stand": POSTURE_STAND,
            "stand" + ASL_STRING_SEPARATOR + "up": POSTURE_STAND}

FS_TRIANGULAR_MF = "triangular_mf"
FS_TRAPEZOIDAL_MF = "trapezoidal_mf"
FS_GAUSSIAN_MF = "gaussian_mf"

FS_POSITIVE_INTERPRETATION_VALUES = ["hpc", "vhpc", "appc", "ppc", "high"]  # todo note "high" should be removed and this should also be checked in general conceptually


NSGA2 = "NSGA2"
RNSGA2 = "RNSGA2"
NSGA3 = "NSGA3"
UNSGA3 = "UNSGA3"
GA = "GA"
DE = "DE"

PHI_INTERPRETABILITY_INDEX = "PHI"
AVG_COVERAGE_INDEX = "COVERAGE"
